---
# tasks file for tailscale

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ tailscale_dependencies }}"

- name: Import Tailscale RPM key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ tailscale_repo_gpgkey }}"
  when:
    - ansible_pkg_mgr in [ "yum", "dnf", "zypper", "dnf5" ]

- name: Add the Tailscale repository (yum/dnf)
  ansible.builtin.yum_repository:
    name: tailscale-stable
    description: Tailscale stable
    baseurl: "{{ tailscale_repo_baseurl }}"
    gpgkey: "{{ tailscale_repo_gpgkey }}"
  when:
    - ansible_pkg_mgr in [ "yum", "dnf", "dnf5" ]

- name: Run apt tasks
  when:
    - ansible_pkg_mgr in [ "apt" ]
  block:
    - name: Add tailscale repository | sources.list
      when:
        - (ansible_distribution == "Debian" and ansible_distribution_version is version('13', '<'))
          or
          (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('24.04', '<'))
      block:
        - name: Add apt key | sources.list
          ansible.builtin.apt_key:
            url: "{{ tailscale_apt_key_url }}"
            keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg

        - name: Add the Tailscale repository (apt) | sources.list
          ansible.builtin.apt_repository:
            repo: "{{ tailscale_apt_repo }}"
            filename: tailscale
          register: _deb_repository

    - name: Add tailscale repository | deb822
      when:
        - (ansible_distribution == "Debian" and ansible_distribution_version is version('13', '>='))
          or
          (ansible_distribution == "Ubuntu" and ansible_distribution_version is version('24.04', '>='))
      block:
        - name: Add the Tailscale repository (apt) | deb822
          ansible.builtin.deb822_repository:
            name: tailscale
            types: deb
            uris: "{{ tailscale_apt_deb822_uri }}"
            suites: '{{ ansible_distribution_release }}'
            signed_by: "{{ tailscale_apt_key_url }}"
            components:
              - main
            state: present
          register: _deb_repository

    - name: Update apt cache  # noqa: no-handler
      ansible.builtin.apt:
        update_cache: true
      when:
        - _deb_repository.changed

- name: Run zypper tasks
  when:
    - ansible_pkg_mgr in [ "zypper" ]
  block:
    - name: Add tailscale repository (zypper)
      community.general.zypper_repository:
        repo: "{{ tailscale_repo_baseurl }}"

    - name: Install tailscale (zypper)
      community.general.zypper:
        name: tailscale

- name: Install tailscale
  ansible.builtin.package:
    name: tailscale
  when:
    - ansible_pkg_mgr not in [ "zypper" ]

- name: Enable and start the server
  ansible.builtin.service:
    name: tailscaled
    state: started
    enabled: true

- name: Modify routing settings
  when:
    - tailscale_exit_node or
      tailscale_advertise_routes | length > 0
  block:
    - name: Install sysctl
      ansible.builtin.package:
        name: "{{ tailscale_sysclt_packages }}"

    - name: Check for /etc/sysctl.d
      ansible.builtin.stat:
        path: /etc/sysctl.d
      register: tailscale_sysctl_d

    - name: Allow forwarding in sysctl.d
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        sysctl_file: "{{ tailscale_sysctl_file }}"
      loop:
        - net.ipv4.ip_forward
        - net.ipv6.conf.all.forwarding
      loop_control:
        label: "{{ item }}"

    - name: Gather the package facts
      ansible.builtin.package_facts:

    - name: Allow masquarading
      ansible.posix.firewalld:
        masquerade: true
        state: enabled
        immediate: true
        permanent: true
      when:
        - "'firewalld' in ansible_facts.packages"

- name: Check tailscale status
  ansible.builtin.command:
    cmd: tailscale status
  register: tailscale_status
  changed_when: false
  failed_when: false

- name: Run tailscale up
  when:
    - "'Logged out.' in tailscale_status.stdout"
    - tailscale_authkey != ""
  block:
    - name: Run tailscale up with authkey
      when:
        - tailscale_advertise_routes | length == 0
      block:
        - name: Run tailscale up regular
          ansible.builtin.command:
            cmd: "{{ tailscale_up_command }}"
          changed_when: true
      rescue:
        - name: Run tailscale up reset
          ansible.builtin.command:
            cmd: "{{ tailscale_up_command }} --reset"
          changed_when: true
    - name: Run tailscale up with advertised routes
      ansible.builtin.command:
        cmd: "{{ tailscale_up_command }} --advertise-routes={{ tailscale_advertise_routes | join(',') }}"
      changed_when: true
      when:
        - tailscale_advertise_routes | length > 0
