---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '39 20 20 * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main

  molecule:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.13"]
        distro:
          - image: "amazonlinux"
            tag: "latest"
          - image: "debian"
            tag: "latest"
          - image: "debian"
            tag: "bullseye"
          - image: "enterpriselinux"
            tag: "latest"
          - image: "fedora"
            tag: "38"
          - image: "fedora"
            tag: "39"
          - image: "ubuntu"
            tag: "latest"
          - image: "ubuntu"
            tag: "jammy"
          - image: "ubuntu"
            tag: "focal"
        exclude:
          # Exclude Amazon Linux from Python 3.13 tests
          - python-version: "3.13"
            distro:
              image: "amazonlinux"
              tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: ansible-role-tailscale

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions ansible-lint molecule molecule-plugins[docker] ansible-core
          if [ -f ansible-role-tailscale/requirements.txt ]; then pip install -r ansible-role-tailscale/requirements.txt; fi
          if [ -f ansible-role-tailscale/requirements.yml ]; then ansible-galaxy install -r ansible-role-tailscale/requirements.yml; fi

          # Create proper role directory structure for molecule
          mkdir -p ~/.ansible/roles
          ln -s ${GITHUB_WORKSPACE}/ansible-role-tailscale ~/.ansible/roles/robertdebock.tailscale

      - name: Test with molecule
        run: |
          cd ansible-role-tailscale
          molecule test
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
          ANSIBLE_ROLES_PATH: ~/.ansible/roles:${GITHUB_WORKSPACE}/ansible-role-tailscale
          image: ${{ matrix.distro.image }}
          tag: ${{ matrix.distro.tag }}
